### ISSUE TITLE
Improve the radix github / radix CLI

### ISSUE THREAD

**Issue by Biosins** [equinor/radix-github-actions#53]
I have just been through the process of creating several applications on Radix that require other CI tools. Part of this requires me to create a deploy pipeline job on radix when the image has been built and pushed to the container registry.

I'm not sure how it could be improved, but the reality was that the most difficult part of the whole process of creating the app was using the Radix actions. It was hard to tell what inputs were required or optional, and what they could be before running the action, which took a few minutes. All of the documentation refers to these actions when it comes to using other CI tools, but they don't provide links to the underlying Radix CLI, to understand what was needed to get it working in the first place.

I apologise for a lack of specificity, and hope that you can understand my difficulties in using the actions

**Comment by emirgens** [comment]
Develop v.2
Use inspiration from [Azure/login](https://github.com/Azure/login)

**Comment by Richard87** [comment]
Upgrade the action to:

- Install rx cli in the workflow
- Optionally Authenticate
- Cleanup step to remove auth

Usage could be:

```yaml
- use: equinor/radix-github-actions@v2
  with:
     authenticate: federated-credentials # client-secret etc
     version: latest

- run: rx validate radix-config
```
